### ISSUE TITLE
CM: Fehler beim Leeren des Symfony Anwendungscache 

### ISSUE THREAD

**Issue by saress** [dalley-it/contao-photoswipe#1]
Leert man via Contao Manager (1.1.7, Contao 4.4.42) den Anwendungscache der Entwicklungsumgebung, dann erhält man folgende Fehlermeldung:

$ /usr/local/bin/php-cli-73-soapssl-nognutls '-q' '/home/fc001hob/www/home/vendor/contao/manager-bundle/bin/contao-console' 'cache:clear' '--env=dev' '--no-warmup' 2>&1

In DebugClassLoader.php line 213:
                                                                               
  The autoloader expected class "Dait\DalleyItPhotoSwipe\DependencyInjection\  
  Configuration" to be defined in file "/home/fc001hob/www/home/vendor/composer/../dalley-it/contao-photoswipe/src/DependencyInjection/  
  Configuration.php". The file was found but the class was not in it, the class name or namespace probably has a typo.                                    
                                                                               
Process terminated with exit code 1
Result: General error

---

Der Hintergrundprozess wurde unerwartet beendet

--

Beste Grüße
Sares

**Comment by saress** [comment]
Der Fehler liegt darin, dass der Namespace in der src/DependencyInjection/Configuration.php Datei nicht angegeben wurde. Ergänzt man: 

`namespace Dait\DalleyItPhotoSwipe\DependencyInjection;`

Funktioniert alles wie gewünscht und erwartet. Wäre super, wenn man das im Bundle ebenfalls ergänzen könnte.

Beste Grüße
Saress

**Comment by dalley-it** [comment]
@saress - vielen Dank für den Hinweis. 

Ich habe die Datei src/DependencyInjection/Configuration.php um den namespace entsprechend ergänzt.

Beste Grüße
dait

**Comment by saress** [comment]
Gern geschehen und vielen Dank für's Fixing! 

Beste Grüße
Saress
